config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from accounts.views import login_view
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("jobs/", include("jobs.urls")),

    # FIXED LOGIN & LOGOUT
    path("login/", login_view, name="login"),
  path(
    "logout/",
    LogoutView.as_view(next_page="login"),
    name="logout"
),


    path("", RedirectView.as_view(url="/jobs/", permanent=False)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    # job seeker
    path("", views.job_list, name="job_list"),
    path("apply/<int:job_id>/", views.apply_job, name="apply_job"),
    path("my-applications/", views.my_applications, name="my_applications"),

    # recruiter
    path("recruiter/", views.recruiter_dashboard, name="recruiter_dashboard"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("create/", views.create_job, name="create"),
    path("applications/<int:job_id>/", views.job_applications, name="job_applications"),
    path("application/accept/<int:app_id>/", views.accept_application, name="accept_application"),
    path("application/reject/<int:app_id>/", views.reject_application, name="reject_application"),
    path("application/<int:app_id>/<str:status>/", views.update_application_status, name="update_application_status"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Job Portal</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% if messages %}
    {% for message in messages %}
        <div style="padding:10px; margin-bottom:10px; border:1px solid #ccc;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/jobs/">Job Portal</a>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ms-auto">

        {% if user.is_authenticated %}

            {% if user.role == "RECRUITER" %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jobs:dashboard' %}">Dashboard</a>
                </li>
            {% endif %}

            {% if user.role == "CANDIDATE" %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jobs:my_applications' %}">My Applications</a>
                </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link text-danger" href="{% url 'logout' %}">Logout</a>
            </li>

        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
    {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
  {% endfor %}
{% endif %}

{% block content %}{% endblock %}
</div>

</body>
</html>